// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdBgw3MU1cSHE4NvR1qEyLhuBmqBjEHV8',
    appId: '1:676059955468:web:8e9402d3fa5f2727d90929',
    messagingSenderId: '676059955468',
    projectId: 'palm-restaurant',
    authDomain: 'palm-restaurant.firebaseapp.com',
    storageBucket: 'palm-restaurant.firebasestorage.app',
    measurementId: 'G-VKMLXBC42T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBI1x6ZUk1pUy6SfhQaENfYRe4xZYh8o0',
    appId: '1:676059955468:android:13724de6e435ff61d90929',
    messagingSenderId: '676059955468',
    projectId: 'palm-restaurant',
    storageBucket: 'palm-restaurant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4WxXdHSKwWs-M-nwkJF_p-UVyIL1Bc2c',
    appId: '1:676059955468:ios:d63773cbdb1ffcc0d90929',
    messagingSenderId: '676059955468',
    projectId: 'palm-restaurant',
    storageBucket: 'palm-restaurant.firebasestorage.app',
    androidClientId: '676059955468-thku2gucjq7i7h6qrcmhsca0c2s8lqma.apps.googleusercontent.com',
    iosClientId: '676059955468-4l462qip2cqlpfmskrlo2go34dfvtvku.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourismApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4WxXdHSKwWs-M-nwkJF_p-UVyIL1Bc2c',
    appId: '1:676059955468:ios:d63773cbdb1ffcc0d90929',
    messagingSenderId: '676059955468',
    projectId: 'palm-restaurant',
    storageBucket: 'palm-restaurant.firebasestorage.app',
    androidClientId: '676059955468-thku2gucjq7i7h6qrcmhsca0c2s8lqma.apps.googleusercontent.com',
    iosClientId: '676059955468-4l462qip2cqlpfmskrlo2go34dfvtvku.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourismApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdBgw3MU1cSHE4NvR1qEyLhuBmqBjEHV8',
    appId: '1:676059955468:web:92c0dbe1ad24ae06d90929',
    messagingSenderId: '676059955468',
    projectId: 'palm-restaurant',
    authDomain: 'palm-restaurant.firebaseapp.com',
    storageBucket: 'palm-restaurant.firebasestorage.app',
    measurementId: 'G-BPNJ69N6QT',
  );

}